In [1]:
import pandas as pd
df = pd.read_csv('finance_loan_portfolio_python_dataset.csv')

In [2]:
df.head()

,Record_ID,Customer_ID,Customer_Name,Age,Gender,City,Employment_Type,Annual_Income_INR,Credit_Score,Loan_Type,...,Late_Payment_Count,Default_Flag,Debt_to_Income_Ratio,Savings_Balance_INR,Investment_Value_INR,Risk_Category,Last_Payment_Date,Payment_Mode,Acquisition_Channel,Branch_Name
0,FIN-00255,CUST-00839,Arjun Gupta,64.0,Female,Jaipur,Self-Employed,679000.0,707.0,Home Loan,...,7,Yes,0.920,42160.72,78362.21,High,2026-05-30,Auto-Debit,Partner,Nagpur Civil Lines
1,FIN-00474,CUST-00508,Rohan Iyer,63.0,Male,Mumbai,Salaried,1275000.0,745.0,Personal Loan,...,0,No,0.386,167007.37,435254.86,Low,2026-07-10,Net Banking,Website,Chennai T Nagar
2,FIN-00725,CUST-00013,Rohan Jadhav,48.0,Female,Lucknow,Government Employee,1390000.0,663.0,Personal Loan,...,2,No,NaN,6378.50,0.00,Low,NaN,UPI,Branch,Nashik Road
3,FIN-00438,CUST-00328,Tanvi Chaudhary,56.0,Male,Nashik,Government Employee,719000.0,695.0,Vehicle Loan,...,1,No,0.689,353397.61,148295.33,Medium,2026-06-24,Auto-Debit,Website,Delhi Connaught Place
4,FIN-00661,CUST-00740,Rahul Iyer,53.0,Female,Nashik,Business Owner,7218000.0,665.0,Home Loan,...,3,No,0.075,1210618.96,1460036.03,Medium,2026-04-24,UPI,Branch,Jaipur C Scheme

In [3]:
df.isnull().sum()

Record_ID                   0
Customer_ID                 0
Customer_Name               0
Age                        28
Gender                     22
City                       32
Employment_Type            25
Annual_Income_INR          34
Credit_Score               42
Loan_Type                   0
Loan_Amount_INR             0
Interest_Rate_Pct          18
Loan_Term_Months            0
Monthly_EMI_INR             0
Disbursement_Date           0
Outstanding_Balance_INR    24
Payment_Status              0
Days_Past_Due               0
Late_Payment_Count          0
Default_Flag                0
Debt_to_Income_Ratio       35
Savings_Balance_INR        31
Investment_Value_INR       32
Risk_Category               0
Last_Payment_Date          27
Payment_Mode               20
Acquisition_Channel         0
Branch_Name                 0
dtype: int64

In [4]:
df["Age"] = df["Age"].fillna(df["Age"].mean())

In [5]:
df["Annual_Income_INR"] = df["Annual_Income_INR"].fillna(df["Annual_Income_INR"].mean())

In [6]:
df["Gender"]=df["Gender"].fillna("Unknown Gender")

In [7]:
df["City"]=df["City"].fillna("Unknown City")

In [8]:
df["Interest_Rate_Pct"] = df["Interest_Rate_Pct"].fillna(df["Interest_Rate_Pct"].mean())

In [9]:
df["Outstanding_Balance_INR"] =df["Outstanding_Balance_INR"].fillna(df["Outstanding_Balance_INR"].mean())

In [10]:
df["Debt_to_Income_Ratio"] =df["Debt_to_Income_Ratio"].fillna(df["Debt_to_Income_Ratio"].mean())

In [11]:
df["Savings_Balance_INR"] =df["Savings_Balance_INR"].fillna(df["Savings_Balance_INR"].mean())

In [12]:
df = df.drop_duplicates()

In [13]:
df.shape

(1200, 28)

In [14]:
df['Gender'].unique()

array(['Female', 'Male', 'Non-Binary', 'Unknown Gender'], dtype=object)

In [15]:
df['Gender'].value_counts()

Gender
Male              584
Female            565
Non-Binary         29
Unknown Gender     22
Name: count, dtype: int64

In [16]:
df.groupby("Gender")["Annual_Income_INR"].max()

Gender
Female            7218000.0
Male              7292000.0
Non-Binary        4404000.0
Unknown Gender    3652000.0
Name: Annual_Income_INR, dtype: float64

In [17]:
df.groupby("Gender")["Loan_Amount_INR"].sum()

Gender
Female             889915000
Male              1038050000
Non-Binary          43260000
Unknown Gender      38810000
Name: Loan_Amount_INR, dtype: int64

In [18]:
df.groupby(["Loan_Type","Risk_Category"])["Loan_Amount_INR"].sum().sort_values(ascending=False)

Loan_Type       Risk_Category
Home Loan       Medium           410075000
                High             383155000
Business Loan   Medium           203630000
Vehicle Loan    Medium           144530000
Home Loan       Low              144405000
Vehicle Loan    Low              106720000
Business Loan   High              87005000
Personal Loan   Low               82290000
                Medium            78310000
Vehicle Loan    High              71910000
Education Loan  High              58830000
                Low               57480000
                Medium            53515000
Business Loan   Low               48055000
Gold Loan       Medium            33705000
Personal Loan   High              26700000
Gold Loan       Low               18480000
                High               1240000
Name: Loan_Amount_INR, dtype: int64

In [19]:
df.groupby(["Loan_Type","Risk_Category"])["Loan_Amount_INR"].sum().sort_values(ascending=False)

Loan_Type       Risk_Category
Home Loan       Medium           410075000
                High             383155000
Business Loan   Medium           203630000
Vehicle Loan    Medium           144530000
Home Loan       Low              144405000
Vehicle Loan    Low              106720000
Business Loan   High              87005000
Personal Loan   Low               82290000
                Medium            78310000
Vehicle Loan    High              71910000
Education Loan  High              58830000
                Low               57480000
                Medium            53515000
Business Loan   Low               48055000
Gold Loan       Medium            33705000
Personal Loan   High              26700000
Gold Loan       Low               18480000
                High               1240000
Name: Loan_Amount_INR, dtype: int64

In [20]:
len(df)

1200

In [21]:
df["Customer_ID"].nunique()

653

In [22]:
(df["Customer_ID"].value_counts()>1).sum()

np.int64(351)

In [23]:
df["Loan_Type"].unique()

array(['Home Loan', 'Personal Loan', 'Vehicle Loan', 'Gold Loan',
       'Education Loan', 'Business Loan'], dtype=object)

In [24]:
df.groupby("Loan_Type").size().sort_values(ascending=False)

Loan_Type
Personal Loan     356
Vehicle Loan      242
Home Loan         204
Business Loan     167
Education Loan    120
Gold Loan         111
dtype: int64

In [25]:
df["Loan_Type"].value_counts()

Loan_Type
Personal Loan     356
Vehicle Loan      242
Home Loan         204
Business Loan     167
Education Loan    120
Gold Loan         111
Name: count, dtype: int64

In [29]:
df.groupby("Payment_Status").size().sort_values(ascending=False)

Payment_Status
On Time    389
Closed     385
Late       229
Missed     197
dtype: int64

In [27]:
df.groupby("Risk_Category").size().sort_values(ascending=False)

Risk_Category
Medium    504
Low       494
High      202
dtype: int64

In [30]:
df.groupby("City").size().sort_values(ascending=False).head(5)

City
Mumbai       217
Pune         166
Bengaluru     85
Delhi         81
Thane         74
dtype: int64

In [32]:
df.groupby("City")["Customer_ID"].nunique().sort_values(ascending=False)

City
Mumbai          189
Pune            152
Bengaluru        81
Delhi            78
Thane            71
Hyderabad        69
Nagpur           60
Chennai          57
Nashik           57
Surat            51
Jaipur           48
Kolkata          47
Lucknow          47
Ahmedabad        46
Indore           45
Unknown City     30
Name: Customer_ID, dtype: int64

In [33]:
df.groupby("Employment_Type").size().sort_values(ascending=False)

Employment_Type
Salaried               538
Self-Employed          208
Business Owner         168
Freelancer             145
Government Employee    116
dtype: int64

In [34]:
df.groupby("Payment_Mode").size().sort_values(ascending=False)

Payment_Mode
Auto-Debit     461
UPI            311
Net Banking    201
Cheque         121
Cash            86
dtype: int64

In [36]:
df.groupby("Acquisition_Channel").size().sort_values(ascending=False)

Acquisition_Channel
Mobile App              372
Branch                  298
Website                 261
Partner                 151
Relationship Manager    118
dtype: int64

In [40]:
df.groupby("Branch_Name").size().sort_values(ascending=False).head(5)

Branch_Name
Nagpur Civil Lines       134
Nashik Road              130
Pune Central             129
Bengaluru MG Road        122
Ahmedabad Navrangpura    120
dtype: int64

In [41]:
df.groupby("Loan_Type")["Loan_Amount_INR"].sum().sort_values(ascending=False)

Loan_Type
Home Loan         937635000
Business Loan     338690000
Vehicle Loan      323160000
Personal Loan     187300000
Education Loan    169825000
Gold Loan          53425000
Name: Loan_Amount_INR, dtype: int64

In [42]:
df.groupby("Loan_Type")["Loan_Amount_INR"].sum().sort_values(ascending=False).head(1)

Loan_Type
Home Loan    937635000
Name: Loan_Amount_INR, dtype: int64

In [44]:
df.groupby("Loan_Type")["Interest_Rate_Pct"].mean().sort_values(ascending=False)

Loan_Type
Business Loan     16.910487
Personal Loan     16.656390
Gold Loan         13.607700
Vehicle Loan      11.806721
Education Loan    11.779373
Home Loan          9.546699
Name: Interest_Rate_Pct, dtype: float64

In [45]:
df.groupby("Loan_Type")["Monthly_EMI_INR"].mean().sort_values(ascending=False)

Loan_Type
Business Loan     84940.635509
Home Loan         58016.474657
Gold Loan         36128.699459
Vehicle Loan      34687.824545
Education Loan    26300.832083
Personal Loan     23593.630899
Name: Monthly_EMI_INR, dtype: float64

In [47]:
df.groupby("Loan_Type")["Outstanding_Balance_INR"].mean().sort_values(ascending=False)

Loan_Type
Home Loan         3.777620e+06
Education Loan    9.177283e+05
Business Loan     7.627392e+05
Vehicle Loan      6.201863e+05
Personal Loan     2.044419e+05
Gold Loan         9.924024e+04
Name: Outstanding_Balance_INR, dtype: float64

In [49]:
df.groupby("Payment_Status")["Outstanding_Balance_INR"].sum().sort_values(ascending=False)

Payment_Status
Missed     4.395105e+08
Late       4.060937e+08
On Time    3.912443e+08
Closed     5.172970e+06
Name: Outstanding_Balance_INR, dtype: float64

In [50]:
df.groupby("Payment_Status")["Outstanding_Balance_INR"].mean().sort_values(ascending=False)

Payment_Status
Missed     2.231018e+06
Late       1.773335e+06
On Time    1.005769e+06
Closed     1.343629e+04
Name: Outstanding_Balance_INR, dtype: float64

In [51]:
df.groupby("Loan_Type")["Credit_Score"].mean().sort_values(ascending=False)

Loan_Type
Vehicle Loan      692.546610
Personal Loan     684.046512
Home Loan         682.393939
Business Loan     681.080247
Education Loan    680.468468
Gold Loan         674.247706
Name: Credit_Score, dtype: float64

In [54]:
df.groupby("Risk_Category")["Debt_to_Income_Ratio"].mean().sort_values(ascending=False)

Risk_Category
High      0.762786
Medium    0.627882
Low       0.331235
Name: Debt_to_Income_Ratio, dtype: float64

In [56]:
df.groupby("Risk_Category")[["Credit_Score","Annual_Income_INR","Loan_Amount_INR"]].mean()

               Credit_Score  Annual_Income_INR  Loan_Amount_INR
Risk_Category
High             635.340206       9.624176e+05     3.113069e+06
Low              719.516736       1.698481e+06     9.259717e+05
Medium           668.118852       1.263373e+06     1.832867e+06

In [57]:
df[df["Risk_Category"]=="High"].groupby("City").size().sort_values(ascending=False)

City
Pune            38
Mumbai          31
Bengaluru       15
Delhi           14
Nashik          14
Nagpur          13
Chennai         12
Lucknow         11
Thane           10
Indore           9
Ahmedabad        7
Kolkata          7
Surat            7
Jaipur           6
Hyderabad        4
Unknown City     4
dtype: int64

In [62]:
df.groupby("Customer_ID")["Loan_Amount_INR"].sum().sort_values(ascending=False).head(10)

Customer_ID
CUST-00049    16020000
CUST-00539    14405000
CUST-00873    13645000
CUST-00174    13095000
CUST-00223    12930000
CUST-00318    12785000
CUST-00528    12565000
CUST-00217    12445000
CUST-00267    12155000
CUST-00867    12080000
Name: Loan_Amount_INR, dtype: int64